In [2]:
import numpy as np

In [5]:
myList = [1,2,3]
myList

[1, 2, 3]

In [6]:
myList[1]

2

In [7]:
np.array(myList)

array([1, 2, 3])

In [8]:
myMatrix = [[1,2,3],[4,5,6],[7,8,9]]
myMatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(myMatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(4)

array([0., 0., 0., 0.])

In [18]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.random.rand(3)

array([0.14444911, 0.37656036, 0.06623804])

In [26]:
np.random.rand(4,4)

array([[0.0289226 , 0.55384848, 0.62330406, 0.06689971],
       [0.57094527, 0.36282495, 0.61114988, 0.14913722],
       [0.10127367, 0.20994936, 0.59976082, 0.44708757],
       [0.49708899, 0.17120642, 0.51137969, 0.86955046]])

In [27]:
np.random.randn(3)

array([-1.2147789 ,  0.1223445 ,  0.49362596])

In [28]:
np.random.randn(4,4)

array([[ 0.01553029, -1.72639438,  0.36579717, -0.19554467],
       [-0.11689902,  0.10334557,  0.24479785, -0.11938542],
       [ 0.26996579, -0.74711577, -3.13485149, -1.13640939],
       [ 0.95474425, -1.07876621, -0.52413507,  1.2990297 ]])

In [34]:
np.random.randint(1, 50)

34

In [35]:
np.random.randint(1, 50, 4)

array([27, 10, 19, 38])

In [36]:
arr = np.arange(10)

In [37]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arrrange = np.random.randint(1,50,5)

In [39]:
arrrange

array([ 9,  1, 20, 44, 30])

In [42]:
arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [43]:
arrrange

array([ 9,  1, 20, 44, 30])

In [44]:
arrrange.max()

44

In [45]:
arrrange.min()

1

In [46]:
arrrange.argmax()

3

In [47]:
arrrange.argmin()

1

In [48]:
arr.shape

(10,)

In [53]:
arr.reshape(1,10).shape

(1, 10)

In [54]:
arr.reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [56]:
arr.dtype

dtype('int64')

# Lecture Jan 11, 2020.

In [7]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr[3]

3

In [9]:
arr[2:4]

array([2, 3])

In [11]:
arr[:4]

array([0, 1, 2, 3])

In [12]:
arr[:4] = 50

In [13]:
arr

array([50, 50, 50, 50,  4,  5,  6,  7,  8,  9])

In [14]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr_copyOriginal = arr[0:4]
arr_copyOriginal

array([0, 1, 2, 3])

In [16]:
arr_copyOriginal[:] = 50

In [17]:
arr_copyOriginal

array([50, 50, 50, 50])

In [18]:
arr

array([50, 50, 50, 50,  4,  5,  6,  7,  8,  9])

In [19]:
arr = np.arange(0,10)
arr_copy = arr.copy()
arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr_copy[:] = 50
arr_copy

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50])

In [21]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr = np.arange(25)
arr_2d = arr.reshape(5,5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
arr_2d[2][2]

12

In [33]:
arr_2d[2,2]

12

In [36]:
arr_2d[2:4,2:]

array([[12, 13, 14],
       [17, 18, 19]])

In [37]:
arr_2d[2:4,1:4]

array([[11, 12, 13],
       [16, 17, 18]])

In [44]:
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [45]:
arr_length = arr2d.shape[1]
arr_length

10

In [46]:
for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [47]:
arr2d[[1,3,5,7]]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [48]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [50]:
arr_new = np.arange(0,10)
arr_new

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
less_Than_Five = arr_new < 5
less_Than_Five

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [54]:
arr_new[less_Than_Five]

array([0, 1, 2, 3, 4])

In [55]:
arr_new + arr_new

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [56]:
arr_new * arr_new

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [57]:
arr_new ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])